import { Book, BorrowedBook, LibrarySettings } from './types';
import { addDays, subDays } from 'date-fns';

export const librarySettings: LibrarySettings = {
  finePerDay: 0.50,
  currency: '$',
  borrowPeriodDays: 14,
};

const bookColors = [
  'bg-amber-700',
  'bg-emerald-800',
  'bg-blue-900',
  'bg-red-800',
  'bg-purple-900',
  'bg-teal-800',
  'bg-orange-800',
  'bg-indigo-900',
];

export const books: Book[] = [
  {
    id: '1',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    isbn: '978-0-06-112008-4',
    totalCopies: 5,
    availableCopies: 3,
    shelfLocation: 'A-12',
    coverColor: bookColors[0],
    replacementCost: 15.99,
  },
  {
    id: '2',
    title: '1984',
    author: 'George Orwell',
    isbn: '978-0-45-152493-5',
    totalCopies: 4,
    availableCopies: 1,
    shelfLocation: 'B-03',
    coverColor: bookColors[1],
    replacementCost: 14.99,
  },
  {
    id: '3',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    isbn: '978-0-14-143951-8',
    totalCopies: 3,
    availableCopies: 0,
    shelfLocation: 'C-07',
    coverColor: bookColors[2],
    replacementCost: 12.99,
  },
  {
    id: '4',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '978-0-74-327356-5',
    totalCopies: 6,
    availableCopies: 4,
    shelfLocation: 'A-05',
    coverColor: bookColors[3],
    replacementCost: 13.99,
  },
  {
    id: '5',
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel García Márquez',
    isbn: '978-0-06-088328-7',
    totalCopies: 2,
    availableCopies: 2,
    shelfLocation: 'D-11',
    coverColor: bookColors[4],
    replacementCost: 16.99,
  },
  {
    id: '6',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    isbn: '978-0-31-676948-0',
    totalCopies: 4,
    availableCopies: 3,
    shelfLocation: 'B-09',
    coverColor: bookColors[5],
    replacementCost: 11.99,
  },
  {
    id: '7',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    isbn: '978-0-06-085052-4',
    totalCopies: 3,
    availableCopies: 1,
    shelfLocation: 'C-14',
    coverColor: bookColors[6],
    replacementCost: 14.99,
  },
  {
    id: '8',
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    isbn: '978-0-54-400341-5',
    totalCopies: 5,
    availableCopies: 2,
    shelfLocation: 'E-02',
    coverColor: bookColors[7],
    replacementCost: 25.99,
  },
];

const today = new Date();

export const borrowedBooks: BorrowedBook[] = [
  {
    id: 'b1',
    bookId: '3',
    book: books[2],
    borrowerName: 'Alice Johnson',
    borrowerId: 'STU001',
    borrowDate: subDays(today, 10),
    dueDate: addDays(today, 1), // Due tomorrow - should show reminder
    status: 'borrowed',
    fineAmount: 0,
  },
  {
    id: 'b2',
    bookId: '2',
    book: books[1],
    borrowerName: 'Bob Smith',
    borrowerId: 'STU002',
    borrowDate: subDays(today, 20),
    dueDate: subDays(today, 6), // Overdue by 6 days
    status: 'overdue',
    fineAmount: 3.00,
  },
  {
    id: 'b3',
    bookId: '7',
    book: books[6],
    borrowerName: 'Carol Williams',
    borrowerId: 'STU003',
    borrowDate: subDays(today, 5),
    dueDate: addDays(today, 9),
    status: 'borrowed',
    fineAmount: 0,
  },
  {
    id: 'b4',
    bookId: '8',
    book: books[7],
    borrowerName: 'David Brown',
    borrowerId: 'STU004',
    borrowDate: subDays(today, 30),
    dueDate: subDays(today, 16),
    status: 'lost',
    fineAmount: 25.99, // Replacement cost
  },
  {
    id: 'b5',
    bookId: '3',
    book: books[2],
    borrowerName: 'Emma Davis',
    borrowerId: 'STU005',
    borrowDate: subDays(today, 12),
    dueDate: addDays(today, 2),
    status: 'borrowed',
    fineAmount: 0,
  },
  {
    id: 'b6',
    bookId: '8',
    book: books[7],
    borrowerName: 'Frank Miller',
    borrowerId: 'STU006',
    borrowDate: subDays(today, 18),
    dueDate: subDays(today, 4), // Overdue by 4 days
    status: 'overdue',
    fineAmount: 2.00,
  },
];
