import { Book, BorrowedBook, LibrarySettings, Department } from './types';
import { addDays, subDays } from 'date-fns';

export const librarySettings: LibrarySettings = {
  finePerDay: 5,
  currency: 'Rs.',
  borrowPeriodDays: 30,
};

export const departments: Department[] = [
  'Computer Science & IT',
  'Electronics & ECE',
  'Electrical',
  'Civil',
  'Mechanical',
  'Mathematics',
];

const departmentColors: Record<Department, string> = {
  'Computer Science & IT': 'bg-blue-800',
  'Electronics & ECE': 'bg-emerald-800',
  'Electrical': 'bg-amber-700',
  'Civil': 'bg-orange-800',
  'Mechanical': 'bg-red-800',
  'Mathematics': 'bg-purple-900',
};

export const books: Book[] = [
  // Computer Science & IT
  {
    id: '1',
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    isbn: '978-0-26-203384-8',
    totalCopies: 5,
    availableCopies: 3,
    shelfLocation: 'CS-A01',
    coverColor: departmentColors['Computer Science & IT'],
    replacementCost: 89.99,
    department: 'Computer Science & IT',
  },
  {
    id: '2',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    isbn: '978-0-13-235088-4',
    totalCopies: 4,
    availableCopies: 1,
    shelfLocation: 'CS-A02',
    coverColor: departmentColors['Computer Science & IT'],
    replacementCost: 45.99,
    department: 'Computer Science & IT',
  },
  {
    id: '3',
    title: 'Database System Concepts',
    author: 'Abraham Silberschatz',
    isbn: '978-0-07-352332-3',
    totalCopies: 3,
    availableCopies: 2,
    shelfLocation: 'CS-B03',
    coverColor: departmentColors['Computer Science & IT'],
    replacementCost: 75.99,
    department: 'Computer Science & IT',
  },
  // Electronics & ECE
  {
    id: '4',
    title: 'Electronic Devices and Circuit Theory',
    author: 'Robert L. Boylestad',
    isbn: '978-0-13-262226-4',
    totalCopies: 6,
    availableCopies: 4,
    shelfLocation: 'EC-A01',
    coverColor: departmentColors['Electronics & ECE'],
    replacementCost: 65.99,
    department: 'Electronics & ECE',
  },
  {
    id: '5',
    title: 'Digital Signal Processing',
    author: 'John G. Proakis',
    isbn: '978-0-13-187374-2',
    totalCopies: 4,
    availableCopies: 2,
    shelfLocation: 'EC-A02',
    coverColor: departmentColors['Electronics & ECE'],
    replacementCost: 85.99,
    department: 'Electronics & ECE',
  },
  {
    id: '6',
    title: 'Microelectronic Circuits',
    author: 'Adel S. Sedra',
    isbn: '978-0-19-932391-1',
    totalCopies: 3,
    availableCopies: 0,
    shelfLocation: 'EC-B01',
    coverColor: departmentColors['Electronics & ECE'],
    replacementCost: 95.99,
    department: 'Electronics & ECE',
  },
  // Electrical
  {
    id: '7',
    title: 'Power System Analysis',
    author: 'Hadi Saadat',
    isbn: '978-0-07-284869-3',
    totalCopies: 4,
    availableCopies: 3,
    shelfLocation: 'EE-A01',
    coverColor: departmentColors['Electrical'],
    replacementCost: 72.99,
    department: 'Electrical',
  },
  {
    id: '8',
    title: 'Electric Machinery Fundamentals',
    author: 'Stephen J. Chapman',
    isbn: '978-0-07-352954-7',
    totalCopies: 5,
    availableCopies: 2,
    shelfLocation: 'EE-A02',
    coverColor: departmentColors['Electrical'],
    replacementCost: 68.99,
    department: 'Electrical',
  },
  // Civil
  {
    id: '9',
    title: 'Structural Analysis',
    author: 'R.C. Hibbeler',
    isbn: '978-0-13-461067-6',
    totalCopies: 4,
    availableCopies: 1,
    shelfLocation: 'CE-A01',
    coverColor: departmentColors['Civil'],
    replacementCost: 78.99,
    department: 'Civil',
  },
  {
    id: '10',
    title: 'Soil Mechanics and Foundations',
    author: 'Muni Budhu',
    isbn: '978-0-47-055684-9',
    totalCopies: 3,
    availableCopies: 3,
    shelfLocation: 'CE-A02',
    coverColor: departmentColors['Civil'],
    replacementCost: 82.99,
    department: 'Civil',
  },
  {
    id: '11',
    title: 'Reinforced Concrete Design',
    author: 'Chu-Kia Wang',
    isbn: '978-0-47-001550-3',
    totalCopies: 4,
    availableCopies: 2,
    shelfLocation: 'CE-B01',
    coverColor: departmentColors['Civil'],
    replacementCost: 69.99,
    department: 'Civil',
  },
  // Mechanical
  {
    id: '12',
    title: 'Engineering Mechanics: Statics',
    author: 'J.L. Meriam',
    isbn: '978-1-11-880739-2',
    totalCopies: 6,
    availableCopies: 4,
    shelfLocation: 'ME-A01',
    coverColor: departmentColors['Mechanical'],
    replacementCost: 74.99,
    department: 'Mechanical',
  },
  {
    id: '13',
    title: 'Thermodynamics: An Engineering Approach',
    author: 'Yunus A. Çengel',
    isbn: '978-0-07-339817-4',
    totalCopies: 5,
    availableCopies: 1,
    shelfLocation: 'ME-A02',
    coverColor: departmentColors['Mechanical'],
    replacementCost: 88.99,
    department: 'Mechanical',
  },
  {
    id: '14',
    title: 'Machine Design',
    author: 'Robert L. Norton',
    isbn: '978-0-13-335671-5',
    totalCopies: 4,
    availableCopies: 2,
    shelfLocation: 'ME-B01',
    coverColor: departmentColors['Mechanical'],
    replacementCost: 92.99,
    department: 'Mechanical',
  },
  // Mathematics
  {
    id: '15',
    title: 'Higher Engineering Mathematics',
    author: 'B.S. Grewal',
    isbn: '978-8-17-409195-5',
    totalCopies: 8,
    availableCopies: 5,
    shelfLocation: 'MA-A01',
    coverColor: departmentColors['Mathematics'],
    replacementCost: 35.99,
    department: 'Mathematics',
  },
  {
    id: '16',
    title: 'Linear Algebra and Its Applications',
    author: 'Gilbert Strang',
    isbn: '978-0-03-010567-8',
    totalCopies: 5,
    availableCopies: 3,
    shelfLocation: 'MA-A02',
    coverColor: departmentColors['Mathematics'],
    replacementCost: 55.99,
    department: 'Mathematics',
  },
  {
    id: '17',
    title: 'Probability and Statistics for Engineers',
    author: 'Ronald E. Walpole',
    isbn: '978-0-32-162911-1',
    totalCopies: 4,
    availableCopies: 2,
    shelfLocation: 'MA-B01',
    coverColor: departmentColors['Mathematics'],
    replacementCost: 62.99,
    department: 'Mathematics',
  },
];

const today = new Date();

export const borrowedBooks: BorrowedBook[] = [
  {
    id: 'b1',
    bookId: '6',
    book: books[5], // Microelectronic Circuits
    borrowerName: 'Alice Johnson',
    borrowerId: 'STU001',
    borrowDate: subDays(today, 10),
    dueDate: addDays(today, 1), // Due tomorrow - should show reminder
    status: 'borrowed',
    fineAmount: 0,
  },
  {
    id: 'b2',
    bookId: '2',
    book: books[1], // Clean Code
    borrowerName: 'Bob Smith',
    borrowerId: 'STU002',
    borrowDate: subDays(today, 20),
    dueDate: subDays(today, 6), // Overdue by 6 days
    status: 'overdue',
    fineAmount: 30,
  },
  {
    id: 'b3',
    bookId: '13',
    book: books[12], // Thermodynamics
    borrowerName: 'Carol Williams',
    borrowerId: 'STU003',
    borrowDate: subDays(today, 5),
    dueDate: addDays(today, 9),
    status: 'borrowed',
    fineAmount: 0,
  },
  {
    id: 'b4',
    bookId: '14',
    book: books[13], // Machine Design
    borrowerName: 'David Brown',
    borrowerId: 'STU004',
    borrowDate: subDays(today, 30),
    dueDate: subDays(today, 16),
    status: 'lost',
    fineAmount: 92.99, // Replacement cost
  },
  {
    id: 'b5',
    bookId: '9',
    book: books[8], // Structural Analysis
    borrowerName: 'Emma Davis',
    borrowerId: 'STU005',
    borrowDate: subDays(today, 12),
    dueDate: addDays(today, 2),
    status: 'borrowed',
    fineAmount: 0,
  },
  {
    id: 'b6',
    bookId: '8',
    book: books[7], // Electric Machinery
    borrowerName: 'Frank Miller',
    borrowerId: 'STU006',
    borrowDate: subDays(today, 18),
    dueDate: subDays(today, 4), // Overdue by 4 days
    status: 'overdue',
    fineAmount: 20,
  },
];
